stages:
  - test
variables:
  ARTIFACT: "*.html"
run_playwright_tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.40.0-jammy
  script:
    - npm install
    - npx playwright install
    - npx playwright test --project=core --grep=@UI
    - ls -al ./playwright-report
    - echo "copy artifact"
    - mkdir $CI_PROJECT_NAME && cat "./playwright-report/index.html" >  $ARTIFACT $CI_PROJECT_NAME/index.html
  allow_failure: true
  tags:
    - preprod
