stages:
  - test
variables:
  ARTIFACT: "*.html"
run_playwright_tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.40.0-jammy
  script:
    - npm install
    - npx playwright install
    - npx playwright test --project=core --grep=@UI
    - ls -al ./playwright-report
    - cat "$CI_PROJECT_NAME/playwright-report/index.html" || echo "not found"
    - cat "./playwright-report/index.html" || echo "not found"

    #- echo "copy artifact"
    #- mkdir $CI_PROJECT_NAME && cp $ARTIFACT $CI_PROJECT_NAME/.
  allow_failure: true
  tags:
    - preprod
