stages:
  - test

variables:
  ARTIFACT: "*.html"
  GREP_OPTION: "@UI"
  PROJECT: "core"

run_playwright_tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.40.0-jammy
  script:
    - npm install
    - npx playwright install
    - npx playwright test --project=$PROJECT --grep=$GREP_OPTION
    - ls -al
    - echo "copy artifact"
    - mkdir $CI_PROJECT_NAME && cp "./playwright-report/index.html" $CI_PROJECT_NAME/index.html
  allow_failure: true
  tags:
    - preprod
  artifacts:
    paths:
      - $CI_PROJECT_NAME/
    expire_in: 7 days
